### ISSUE TITLE
ImportError with scripts/mm2s_unpickle.py

### ISSUE THREAD

**Issue by Cypouz** [LAKostis/mailman2sympa#7]
I get an `ImportError` with `scripts/mm2s_unpickle.py`:

```
Traceback (most recent call last):
  File "./scripts/mm2s_unpickle.py", line 14, in <module>
    config_dict = pickle.load(infile)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named Mailman.Bouncer
```

I solved the problem by importing the `Mailman.Bouncer` module by adding those lines in `scripts/mm2s_unpickle.py`:

```
sys.path.append('/usr/lib/mailman')
import Mailman.Bouncer
```

**Comment by LAKostis** [comment]
Hey! Could you create a PR for this?

**Comment by Cypouz** [comment]
It's not really a daily routine but I can try 😅 But I'm not really sure that my solution is the best one and doesn't add other side-effect...

By the way, I think that my `sys.path.append('/usr/lib/mailman')` looks similar to the `sys.path.insert(1,mm_path)` already there...

**Comment by Cypouz** [comment]
In fact, `mm_path=os.getenv('MAILMAN_HOME', '/usr/share/mailman')` doesn't load the `MAILMAN_HOME` bash-variable defined in `conf/mailman2sympa.conf`.

**Comment by Cypouz** [comment]
Only changing `MAILMAN_HOME=/usr/lib/mailman` to `export MAILMAN_HOME=/usr/lib/mailman` in `conf/mailman2sympa.conf` solve the problem. Unless there is another more elegant method to reach the `MAILMAN_HOME` bash-variable into `scripts/mm2s_unpickle.py`?

I suppose it's to be modified in `conf/mailman2sympa.conf.debian`. But what about `conf/mailman2sympa.conf.local` and `conf/mailman2sympa.conf.alt`?

**Comment by LAKostis** [comment]
mailman2sympa.conf.alt is ALTLinux specific and that worked last time. I'll check again. Sorry for delay in answering, wasn't looking into this for months.

**Comment by tarheelcoxn** [comment]
> 
> ```
> sys.path.append('/usr/lib/mailman')
> import Mailman.Bouncer
> ```

Just to "me too" ... we had the same error and this worked to move us forward.
